services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-service-app
    ports:
      - "8101:8000"
    depends_on:
      - db
      # - redis
    volumes:
      - .:/app
    networks:
      - foroshgahman-shop-service-network

  # redis:
  # image: "redis:alpine"
  # container_name: shop-service-redis
  # volumes:
  # - redis-data:/data
  # networks:
  # - foroshgahman-shop-service-network
  # healthcheck:
  # test: ["CMD", "redis-cli", "ping"]
  # interval: 10s
  # timeout: 5s
  # retries: 5

  db:
    image: postgres:17
    container_name: shop-service-db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foroshgahman-shop-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  # redis-data:

networks:
  foroshgahman-shop-service-network:
