services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-service-app
    ports:
      - "8101:8000"
    depends_on:
      shop-db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - foroshgahman-microservices
    environment:
      RABBITMQ_HOST: rabbitmq
      DEBUG: ${DEBUG}

  shop-db:
    image: postgres:17
    container_name: shop-service-db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres-data2:/var/lib/postgresql/data
    networks:
      - foroshgahman-microservices
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data2:

networks:
  foroshgahman-microservices:
    external: true
